### PR TITLE
Properly add iPhone 6 app icon and splash screen sizes

### PR DESCRIPTION
**Pull request by shanesmith**
Pull request #128 made changes to the js instead of the source coffee files. This fixes that.

### CODE REVIEW

**Comment by rgarver** [comment]
:+1:

**Comment by johnhornsby** [comment]
Is this being done?

**Comment by sdhull** [comment]
:+1:

**Comment by levexis** [comment]
Hi guys I inherited access to this project but have fallen out of love with phonegap. Is anyone keen to take ownership of this? I'll take a quick look but I don't have access to the npm account even if I merge to master.

**Comment by shanesmith** [comment]
@levexis I wouldn't mind taking over, at least for the short term =)

**Pull request merged**
