### PR TITLE
Added iPhone 6 and 6+ splash screens

### PR DESCRIPTION
**Pull request by optikalefx**

### CODE REVIEW

**Comment by gabrielpoca** [comment]
hey @optikalefx , can I close this pr?

**Comment by optikalefx** [comment]
@gabrielpoca This is ready for the merge

**Comment by gabrielpoca** [comment]
@optikalefx but it doesn't have any changes, or am I missing something?

**Comment by optikalefx** [comment]
Maybe I'm missing something. I added https://github.com/optikalefx/grunt-phonegap/blob/1c818da3a42f9769f515aaab5da821b6a212fc6a/tasks/build/after/local/ios/screens.js#L51-L60
Maybe this was added later.

**Comment by gabrielpoca** [comment]
Not sure what's happening. I'm sorry for the extra work, but could you rebase?

**Comment by optikalefx** [comment]
I can't this second, but check this commit, it's the same change

https://github.com/zipscene/grunt-phonegap/commit/aa82fa61d9a78a801c7d1fce142e9de83b3b86f8

**Pull request closed without merging**
